### ISSUE TITLE
Models weights available?

### ISSUE THREAD

**Issue by VladVin** [samsledje/ConPLex#21]
Hello @samsledje !
I like the paper, the project and the way you set up this repository with the CI/CD and packaging. I would like to use your models for protein and ligand embeddings extraction to test ConPLex within my benchmark. How can I get access to the models' weights?

**Comment by samsledje** [comment]
Hi @VladVin, weights for the pre-trained model we used to do experimental validation can be `conplex-dti download`-ed, or if you want to train on a specific data set, it is pretty fast and lightweight to `conplex-dti train` a new model -- although right now we only have the benchmark data sets implemented as training data, and it is more difficult to substitute in your own data. This is something we're working on though!

**Comment by VladVin** [comment]
Great! I din't notice there's a weights link in the code base. Thank you!
