### ISSUE TITLE
Fine-tuning ConPLex on custom datasets

### ISSUE THREAD

**Issue by seyonechithrananda** [samsledje/ConPLex#26]
Is there any plans to support custom dataset contrastive fine-tuning? And if not, do you have any advice on good first steps to do so ourselves?

**Comment by samsledje** [comment]
Hi @seyonechithrananda ,

Custom training data for both binary and contrastive training is on our list, but is currently lower priority as we're currently focused more on making the inference mode with pre-trained models available. To get started yourself, I'd recommend looking at the [ContrastiveDataset](https://github.com/samsledje/ConPLex/blob/main/conplex_dti/dataset/datamodules.py#L155) and [DUDEDataModule](https://github.com/samsledje/ConPLex/blob/main/conplex_dti/dataset/datamodules.py#L606) classes. These are a good place to get started for defining your own contrastive fine-tuning data sets, as they should have the same functionality as this DataModule, which is created [here in training](https://github.com/samsledje/ConPLex/blob/main/conplex_dti/cli/train.py#L342).
