### ISSUE TITLE
[ERROR] Unable to download davis/train.csv - <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by AaronYoooooooog** [samsledje/ConPLex#29]

**Comment by AaronYoooooooog** [comment]
conplex-dti download --to datasets --benchmarks davis bindingdb biosnap biosnap_prot biosnap_mol dude

**Comment by samsledje** [comment]
Could you please provide more information on how to replicate this?

**Comment by samsledje** [comment]
This is likely an issue with the internet connection -- I'm going to close the issue, please feel free to re-open if you have more information on replicating this issue.
