### ISSUE TITLE
About the bindingdb training set

### ISSUE THREAD

**Issue by zh2417** [samsledje/ConPLex#31]
Why did you only use a portion of the bindingdb dataset for training? As far as I know, this dataset is large and seems to have approximately 2 million molecules related to the target. Looking forward to your reply

**Comment by zh2417** [comment]
Hello, I would like to know how you can obtain the label for the bindingdb dataset，
![image](https://github.com/samsledje/ConPLex/assets/72326396/7e872a43-ecaa-426c-82f8-e84b6765ec97)
What are the values of threshold and y？thanks

**Comment by samsledje** [comment]
The binary data sets were taken from [MolTrans](https://github.com/kexinhuang12345/MolTrans/tree/master/dataset) for comparison, please consult their report for more detailed information on data set generation.

The affinity data was taken from the [Therapeutics Data Commons DTI DG benchmark](https://tdcommons.ai/benchmark/dti_dg_group/overview/)
