### ISSUE TITLE
When the training epoch exceeds 50, using the relu activation function may cause some problems

### ISSUE THREAD

**Issue by zh2417** [samsledje/ConPLex#32]
## 🐛 Bug Report
when I used cuda，in epoch 67，bingingdb dataset，I added  dropout 
![image](https://github.com/samsledje/ConPLex/assets/72326396/34b0569b-ab6f-4dd7-b6a6-d8b78f77558c)

when using cpu  in epoch 147，without dropout 
![image](https://github.com/samsledje/ConPLex/assets/72326396/7b4b9c63-6d45-4f21-8cfb-d19f712ca618)
Why is this happening

**Comment by samsledje** [comment]
Hm, this should not be happening -- there is a ReLU activation immediately prior to the cosine distance calculation, which should have all values between 0-1. Can you provide the configuration file you are using so I can try to replicate this? Thanks.

**Comment by zh2417** [comment]
You can "docker pull zhanghang22/conplex_idelta:v2" and "cd conplex", type "poetry shell" to activate envirnment.
using bindingdb dataset. set up epoch 200.  I meet this error  at epoch 139.
When I replaced the activation function with sigmoid, I did not encounter this problem.
![image](https://github.com/samsledje/ConPLex/assets/72326396/738a9bdc-b175-4557-92f9-0578d6e50501)
sorry to bother you,thank you very much.
