### ISSUE TITLE
Cannot run the package 

### ISSUE THREAD

**Issue by ChenyuL** [samsledje/ConPLex#33]
<img width="1442" alt="image" src="https://github.com/samsledje/ConPLex/assets/17032366/5cd4f12b-c671-41d2-9a9a-ef4130cb705e">

Dear authors!   I was trying to download the benchmark data and pre-trained model but faild. Could you please help me with the debugging? Thank you!

**Comment by samsledje** [comment]
Fixed in v0.1.10, thanks for bringing this to my attention!
