### ISSUE TITLE
how to use the results.tsv

### ISSUE THREAD

**Issue by Saoge123** [samsledje/ConPLex#36]
Thanks for your impressive work. I run the command of prediction and got the 'results.tsv'.
This file contian 3 colunms, the last col should be the distance between ligand and protein embedding.

lig-5092	Protein1	0.0
C43734921	Protein1	0.0
C51120531	Protein1	0.0
C63349888	Protein1	0.004318551
C50397193	Protein1	0.013059744

What is the threshold of this distance? e.g.  a value less than that is considered a positive sample, and vice versa.

**Comment by samsledje** [comment]
ConPLex scores are generally well-calibrated, such that the values between 0-1 roughly correlate to model confidence/likelihood of an interaction. In the default case, where the model is in classification mode and the latent distance is the cosine similarity, you can think of values closer to one as more likely to interact. I'd recommend against a strict cutoff, and say that ConPLex is best used for large-scale screens and relative probability/ranking interactions.
