### ISSUE TITLE
GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

### ISSUE THREAD

**Issue by CCEB1996** [samsledje/ConPLex#37]
When I run the train.py file, it prompts this error GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU. How to solve this problem

**Comment by samsledje** [comment]
Please post the command you ran and the corresponding stack trace/error, and I can try to help you debug.

**Comment by CCEB1996** [comment]
> Please post the command you ran and the corresponding stack trace/error, and I can try to help you debug.

command: conplex-dti train --run-id TestRun --config config/default_config.yaml

![image](https://github.com/user-attachments/assets/18c5ac26-6afd-4b7c-92c0-9383324046a1)

**Comment by samsledje** [comment]
Can you post the specs of the system you are running on? It looks like you are running on Windows, on which ConPLex has not previously been tested. It appears that Pytorch is able to find the cuda:0 GPU, so it is possible you will be able to ignore this error message as the model is loaded on CPU, then later moved to GPU. Do you see GPU utilization (`nvidia-smi`) when running?

**Comment by CCEB1996** [comment]
> Can you post the specs of the system you are running on? It looks like you are running on Windows, on which ConPLex has not previously been tested. It appears that Pytorch is able to find the cuda:0 GPU, so it is possible you will be able to ignore this error message as the model is loaded on CPU, then later moved to GPU. Do you see GPU utilization (`nvidia-smi`) when running?

The system I run the code on is Windows. When I was training, I checked the GPU usage and it was very little.

**Comment by CCEB1996** [comment]
It looks like the pipe parameter is not used and is not instantiated in train.py
![image](https://github.com/user-attachments/assets/7ec6412c-b222-4576-b8ce-96557225d6dd)

**Comment by samsledje** [comment]
I think you can safely ignore this error-- the pipeline is not originally on GPU when it is created, but then is moved to GPU when the model is registered with CUDA (line 175 in the screenshot you posted). This warning is likely coming when the pipeline is initially created, in the init. My guess is this is a warning that was either added in more recent versions of transformers, or is Windows specific; either way it should be able to be ignored safely.
